# try:
#     print(10/0)
# except:
#     print("zero error")
# ===============================================

# a=1
# try:
    # print(a) #<--NameError
    # print(435/0) #<--ZeroDivisionError
    # num=int(input("Enter number : "))  #<-- Value Error
    # a = "hfhhfhfhf/hf" #<--Type error
    # print(a+12)       #<--Type Error

# except NameError:
#     print("name error")

# except ZeroDivisionError:
#     print("ZeroDivisionError")

# except ValueError:
#     print("Value Error")

# except TypeError:
#     print("Type Error")

#--------------------------------------
# try:
#     print(1/0)
# except:
#     print("except")

# else:
#     print("else")


# finally:
#     print("finally")





   

# try:
#     # Code that may raise an exception
#     result = 10 / 0
# except ZeroDivisionError:
#     # Handle the specific exception
#     print("Error: Division by zero!")



# try:

#     if number < 0:
#         print("The number is negative.")
# except:
    
#     print("The number is Positive")